config/routes.rb
Rails.application.routes.draw do

  get 'recipes/index'
  get 'recipes/new'
  get 'recipes/create'
  get 'recipes/edit'
  get 'recipes/update'
  get 'recipes/delete'

  get 'recipes/new_recipe'
  get 'recipes/new_recipe2'
  get 'recipes/rank_day', to: 'recipes#rank_day'
  get 'recipes/rank_week', to: 'recipes#rank_week'
  get 'recipes/menu', to: 'recipes#menu'
  get 'recipes/prof'
  get 'recipe_search', to: 'recipes#recipe_search'


  devise_for :users
  resources :recipes do
    get "favorites/toggleFav"
  end

  root to:'recipes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :img, ImgUploader

  belongs_to :user

  has_many :zairyos, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :zairyos, allow_destroy: true

  has_many :recipekinds, dependent: :destroy
  accepts_nested_attributes_for :recipekinds, allow_destroy: true

  has_many :recipeprocesses, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :recipeprocesses, allow_destroy: true

  has_many :favorites, dependent: :destroy
end

app/models/recipekind.rb
class Recipekind < ApplicationRecord
  belongs_to :recipe
end

app/models/recipeprocess.rb
class Recipeprocess < ApplicationRecord
  mount_uploader :process_img, ImgUploader
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def email_required?
    false
  end
  def email_changed?
    false
  end
  #has_many :recipes
end

app/models/zairyo.rb
class Zairyo < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def toggleFav
    recipe_id = params[:recipe_id]
    user_favorites = current_user.favorites

    if user_favorites.exists?(recipe: recipe_id)
      user_favorites.where(recipe: recipe_id).destroy_all
    else
      user_favorites.create(user: current_user, recipe: Recipe.find(recipe_id))
      
    end

    render :nothing => true
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  # GET /recipes
  # GET /recipes.json
  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result.includes(:user).paginate(page: params[:page], per_page: 3).order(created_at: :desc)
    @recipes_new = @q.result.includes(:user).paginate(page: params[:page], per_page: 4).order(created_at: :desc)
    @day_ranking = Favorite.includes(:recipe).where(created_at: Date.today.all_day).group(:recipe_id).order("count(*) desc").limit(3)
    threedays_menu
  end


  def new_recipe
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result.includes(:user).paginate(page: params[:page], per_page: 9).order(created_at: :desc)
    @page= @recipes.current_page
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @q = Recipe.ransack(params[:q])
  end

  # GET /recipes/new
  def new
    @q = Recipe.ransack(params[:q])
    if user_signed_in?
      @recipe = Recipe.new
      @recipe.recipekinds.build
    else
      redirect_to new_user_registration_path, notice:"会員のみレシピ投稿ができます！"
    end
  end

  # GET /recipes/1/edit
  def edit
    @q = Recipe.ransack(params[:q])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @q = Recipe.ransack(params[:q])
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'レシピを投稿しました！' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    @q = Recipe.ransack(params[:q])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'レシピの編集が完了しました！' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'レシピを削除しました！' }
      format.json { head :no_content }
    end
  end

  def recipe_search
    @q = Recipe.search(params[:q])
    @recipes = @q.result.includes(:user).paginate(page: params[:page], per_page: 9).order(created_at: :desc)
    @page = @recipes.current_page
    @recipes_all = Recipe.includes(:user).paginate(page: params[:page], per_page: 9).order(created_at: :desc)
  end

  def rank_day
    @q = Recipe.ransack(params[:q])
    ranks
  end

  def rank_week
    @q = Recipe.ransack(params[:q])
    ranks
  end

  def menu
    @q = Recipe.ransack(params[:q])
    threedays_menu
  end

  def prof
    @q = Recipe.ransack(params[:q])
  end

  private

    def threedays_menu
      @main = Recipekind.includes(:recipe).where(kind: 'ご飯').order("RANDOM()").limit(3)
      @side = Recipekind.includes(:recipe).where(kind: 'おかず').order("RANDOM()").limit(3)
      @soup = Recipekind.includes(:recipe).where(kind: '汁物').order("RANDOM()").limit(3)
    end

    def ranks
      @week_ranking = Favorite.includes(:recipe).where(created_at: Date.today.all_week).group(:recipe_id).order("count(*) desc").limit(12)
      @day_ranking = Favorite.includes(:recipe).where(created_at: Date.today.all_day).group(:recipe_id).order("count(*) desc").limit(12)
    end

    def search_params
      params.require(:q).permit(:title_cont)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:user_id, :title, :img, :img_cache, :remove_img, :cook_min,
         zairyos_attributes: [:id, :name, :kosu, :_destroy],
         recipekinds_attributes: [:id, :kind],
         recipeprocesses_attributes: [:id, :process_txt, :process_img, :_destroy, :remove_process_img, ])
    end
end

app/controllers/userprof_controller.rb
class UserprofController < ApplicationController

def prof
  @user = User.find(current_user.id)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper

  def favorite_icon(recipe, user)
    if user
      if user.favorites.exists?(recipe: recipe)
        '<i class="fas fa-heart"></i>'
      else
        '<i class="far fa-heart"></i>'
      end
    end
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/userprof_helper.rb
module UserprofHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<style>
  .logo-top{
    text-align:center;
  }

  .nav-item a{
    color:white;
    font-weight:bold;
  }

  .nav-item a:hover{
    color:#f8b862;
    font-weight:bold;
    text-decoration:none;
  }
</style>


<html>
  <head>
    <title>Teamcook</title>
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!--メニューバー---------------------------------------------->

    <div class="top_bar">
      <nav class="navbar navbar-expand-xs navbar-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <div class='swanky'>
            <div class='swanky_wrapper' style="width:100%; height:100%;">

              <%= link_to root_path do %>
                <div class='logo-top'>
                  <%= image_tag 'logo.png', :size =>'110x120' %>
                </div>
              <% end %>

              <%= link_to root_path do %>
                <label for='Home'>
                  <%= fa_icon("home") %>&emsp;&ensp;<b>ホーム</b>
                  <div class='bar'></div>
                </label>
              <% end %>

              <%= link_to recipes_new_recipe_path do %>
                <label for='New'>
                  <i class="fas fa-star"></i>&emsp;&ensp;<b>新着レシピ</b>
                  <div class='bar'></div>
                </label>
              <% end %>

              <span class="checkbox_hidden">
                <input id='Ranking_top' name='checkbox' type='checkbox'>
                <label for='Ranking_top'>
                  <i class="fas fa-crown"></i>&emsp;&ensp;<b>ランキング</b>
                  <div class='lil_arrow'></div>
                  <div class='bar'></div>
                  <div class='swanky_wrapper__content'>
                    <ul>
                      <%= link_to recipes_rank_day_path do %><li>日別ランキング</li><% end %>
                      <%= link_to recipes_rank_week_path do %><li>週間ランキング</li><% end %>
                    </ul>
                  </div>
                </label>
              </span>

              <%= link_to recipes_menu_path do %>
                <label for='Menu'>
                  <i class="fas fa-utensils"></i>&emsp;&ensp;<b>3Days メニュー</b>
                  <div class='bar'></div>
                </label>
              <% end %>

            </div>
          </div>
        </div>

      </nav>
    </div>

    <div class="side-menu">
      <div class='swanky'>
        <div class='swanky_wrapper'>

          <%= link_to root_path do %>
            <div class='logo'>
              <%= image_tag 'logo.png', :size =>'220x240' %>
            </div>
          <% end %>

          <%= link_to root_path do %>
            <label for='Home'>
              <%= fa_icon("home") %>&emsp;&ensp;<b>ホーム</b>
              <div class='bar'></div>
            </label>
          <% end %>

          <%= link_to recipes_new_recipe_path do %>
            <label for='New'>
              <i class="fas fa-star"></i>&emsp;&ensp;<b>新着レシピ</b>
              <div class='bar'></div>
            </label>
          <% end %>

          <span class="checkbox_hidden">
            <input id='Ranking' name='checkbox' type='checkbox'>
            <label for='Ranking'>
              <i class="fas fa-crown"></i>&emsp;&ensp;<b>ランキング</b>
              <div class='lil_arrow'></div>
              <div class='bar'></div>
              <div class='swanky_wrapper__content'>
                <ul>
                  <%= link_to recipes_rank_day_path do %><li>日別ランキング</li><% end %>
                  <%= link_to recipes_rank_week_path do %><li>週間ランキング</li><% end %>
                </ul>
              </div>
            </label>
          </span>

          <%= link_to recipes_menu_path do %>
            <label for='Menu'>
              <i class="fas fa-utensils"></i>&emsp;&ensp;<b>3Days メニュー</b>
              <div class='bar'></div>
            </label>
          <% end %>

        </div>
      </div>
    </div>

      <div class="row" style="float:right; margin:50px 140px 50px 0;">
        
        <div class="icon">
          <!--検索---------------------------------------------->
          <% if user_signed_in? %>
            <span class="button_tooltip" data-toggle="tooltip" title="検索">
              <a data-toggle="collapse" data-target="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" style="text-decoration:none;">
                <i class="fas fa-search"></i>
              </a>
            </span>
          <% end %>

          <% if user_signed_in? %>
            <!--ログアウト---------------------------------------------->
            <span class="button_tooltip" data-toggle="tooltip" title="ログアウト">
              <%= link_to destroy_user_session_path, :method => :delete , data: { confirm: 'ログアウトしますか' }, :style=>"text-decoration:none;" do %>
                <i class="fas fa-sign-out-alt"></i>
              <% end %>
            </span>
          <% else %>
            <!--ログイン---------------------------------------------->
            <span class="button_tooltip" data-toggle="tooltip" title="ログイン">
              <%= link_to new_user_session_path, :method => :new, :style=>"text-decoration:none;" do %>
                <i class="fas fa-sign-in-alt"></i>
              <% end %>
            </span>
          <% end %>

          <% if user_signed_in? %>
            <!--レシピ投稿---------------------------------------------->
            <span class="button_tooltip" data-toggle="tooltip" title="レシピの投稿">
              <%= link_to new_recipe_path, :style=>"text-decoration:none;" do %>
                <i class="fas fa-edit"></i>
              <% end %>
            </span>
          <% else %>
            <!--新規登録---------------------------------------------->
            <a href= '/users/sign_up'>
              <span class="button_tooltip" data-toggle="tooltip" title="新規登録">
                <i class="fas fa-user-plus"></i>
              </span>
            </a>
          <% end %>

          <% if user_signed_in? %>
            <!--プロフィール---------------------------------------------->
            <span class="button_tooltip" data-toggle="tooltip" title="プロフィール">
              <%= link_to recipes_prof_path, :style=>"text-decoration:none;" do %>
                <i class="fas fa-user"></i>
              <% end %>
            </span>
          <% end %>

          <!--検索欄---------------------------------------------->
          <div class="collapse" id="collapseExample">
            <br>
            <div class="form">
              <div class="form-panel one">

                <div class="form-content">
                  <% if user_signed_in? %>
                  <%= search_form_for(@q, url:recipe_search_path) do |f| %>
                    <div class="form-group">
                      <label for="username"><%= f.label :title_cont, '料理の名前' %></label>
                      <%= f.search_field :title_cont, :placeholder => "キーワードを入力" %>
                    </div>

                    <div class="form-group">
                      <%= f.submit '検索',:class => 'button4' %>
                    </div>
                  <% end %>
                  <% end %>
                </div>

              </div>
            </div>

            <br>
          </div>

        </div>
      </div>

      <!--3コラム目(コンテンツ)---------------------------------------------->
      <div class="row justify-content-center">
        <div class="col justify-content-center">
        </div>
        <div class="col justify-content-center">
          <%= yield %>
        </div>
      </div>

    <!--フッダー---------------------------------------------->
    <div class="row justify-content-md-center">
      <br><br><br><br><br>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>
</html>

app/views/recipes/_recipe_search_form.html.erb
<style>
  .form{
    padding: 0 30px;
  }
</style>

<div class="row" style="margin:20px;">
  <div class="col">

    <div class="form">
      <div class="form-panel one">

        <div class="form-content">

          <%= search_form_for(@q, url:recipe_search_path) do |f| %>
            <div class="form-group">
              <label for="username"><%= f.label :title_cont, '料理の名前' %></label>
              <%= f.search_field :title_cont, :placeholder => "キーワードを入力" %>
            </div>

            <div class="form-group">
              <%= f.submit '検索',:class => 'button4' %>
            </div>

          <% end %>
        </div>

      </div>

    </div>

  </div>
</div>

app/views/recipes/_recipeprocess_fields.html.erb
<style>
  i.fas.fa-trash-alt {
  	font-size: 1rem;
    margin:10px;
  	color: #543f32;
    background-color:#f8b862;
  	position:relative;
    float:right;
  	border-radius: 50%;
  	padding: 10px;
  	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
  	transition: color 0.2s ease, background-color 0.2s ease, transform 0.3s ease;
  }

  i.fas.fa-trash-alt:hover {
    background-color:#a22041;
  	color:white;
  	cursor:pointer;
  	box-shadow:none;
  }
</style>

<script>
  $(function(){
    $('#process_img').change(function(e){

      var file = e.target.files[0];
      var reader = new FileReader();

      if(file.type.indexOf("image") < 0){
        alert("画像ファイルを指定してください。");
        return false;
      }

      reader.onload = (function(file){
        return function(e){
          $("#process_img").attr("src", e.target.result);
          $("#process_img").attr("title", file.name);
        };
      })(file);
      reader.readAsDataURL(file);

    });
  });

  $('input[id=lefile]').change(function() {
    $('#photoCover').val($(this).val());
  });
</script>

<div class="nested-fields">
  <%= link_to_remove_association f  do %>
    <i class="fas fa-trash-alt" style="left:-10px;"></i>
  <% end %>
  <div class="form-group" style="width:550px; margin:auto;">
    <%= f.text_field :process_txt %>
    <br>
    <% if false %>
      <label><%= f.label "画像" %></label>
      <%= f.file_field :process_img %>
      <img id="process_img" style="width:400px;height:300px;">
    <% end %>

    <% if false %>
    <div class="row">
      <p><%= f.check_box :remove_process_img %>&ensp;画像を削除する</p>
      <div class="visibility"><%= f.file_field :process_img, id: :process_img %></div>
      <%= image_tag f.process_img.url, id: :img_prev if f.process_img? %>
      <span class="button_tooltip" data-toggle="tooltip" title="写真をアップロード">
        <span onclick="$('#process_img').click();">
          <i class="fas fa-file-upload"></i>
        </span>
      </span>
    </div>
    <% end %>
  </div>
  <br>
</div>

app/views/recipes/_zairyo_fields.html.erb
<style>
  ul li {
    position: relative;
    line-height:2.5em;
    font-weight: bold;
  }
  ul li::after {
    display: block;
    content: '';
    position: absolute;
    line-height:2.5em;
    top: .5em;
    left: -1em;
    width: 8px;
    height: 1px;
    background-color: #666;
    justify-content:center;
  }

  i.fas.fa-trash-alt {
  	font-size: 1rem;
  	color: #543f32;
    background-color:#f8b862;
  	position: relative;
    left:10px;
    bottom:7px;
  	border-radius: 50%;
  	padding: 10px;
  	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
  	transition: color 0.2s ease, background-color 0.2s ease, transform 0.3s ease;
  }

  i.fas.fa-trash-alt:hover {
    background-color:#a22041;
  	color:white;
  	cursor:pointer;
  	box-shadow:none;
  }
</style>

<div class="nested-fields">
  <ul>
    <div class="form-group" style="flex-wrap:nowrap; width:300px; margin:auto;">
      <li>
        <label><%= f.label "材料" %></label>
        <%= f.text_field :name %>
        <br>
        <label><%= f.label "数量" %></label>
        <%= f.text_field :kosu %>
      </li>
      <%= link_to_remove_association f  do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
    <br>
  </ul>
</div>

app/views/recipes/edit.html.erb
<div class="row" style="margin:20px; width:800px;">
  <div class="col" style="width:600px;">

    <h3><span>レシピの編集&ensp;<i class="fas fa-pencil-alt"></i></span></h3>
    <br>
    <%= render 'form', recipe: @recipe %>
    <div class="row">
      <%= link_to '表示', @recipe %> |
      <%= link_to '削除', @recipe, method: :delete, data: { confirm: '本当に削除しますか' } %> |
      <%= link_to '戻る', recipes_path %>
    </div>

  </div>
  <div class="col" style="width:100px;">
  </div>
</div>

app/views/recipes/new.html.erb
<div class="row" style="margin:20px; width:800px;">
  <div class="col" style="width:600px;">

    <h3><span>新しくレシピを投稿&ensp;<i class="fas fa-plus-circle"></i></span></h3>
    <br>
      <%= render 'form', recipe: @recipe %>
  </div>
  <div class="col" style="width:100px;">
  </div>
</div>

app/views/recipes/show.html.erb
<style>
  .day {
    border-bottom: solid 3px #664032;
    position: relative;
    font-size:1.5em;
  }

  .day:after {
    position: absolute;
    content: " ";
    display: block;
    border-bottom: solid 3px #f8b862;
    bottom: -3px;
    width: 30%;
  }

  ul li {
    position: relative;
    line-height:1.5em;
    font-weight: bold;
  }
  ul li::after {
    display: block;
    content: '';
    position: absolute;
    line-height:1.5em;
    top: 1em;
    left: -1em;
    width: 8px;
    height: 1px;
    background-color: #666;
  }

  .box1{
    min-height:280px;
    width:190px;
    padding: 1em 1em;
    color: #5d627b;
    background: white;
    border-top: solid 5px #df8663;
    box-shadow: 0 3px 5px rgba(0, 0, 0, 0.22);
    font-size:0.8rem;
  }

  .fas.fa-pencil-alt{
    position:relative;
    float:right;
    top:3px;
    color:#543f32;
  }

  .fas.fa-pencil-alt:hover{
    color:#a22041;
  }

  .count{
    position:relative;
    float:right;
    color:#a22041;
  }

  .count a{
    color:#a22041;
    text-decoration:none;
  }

  .count:hover{
    content:'';
    color:#543f32;
  }

  .count a:hover{
    color:#543f32;
    text-decoration:none;
  }

  .fas.fa-stopwatch {
    color:#543f32;
    float:right;
  }
</style>

<div class="row" style="margin:20px 50px; width:800px;">
  <div class="col">

    <h3><span>レシピ紹介&ensp;<i class="fas fa-tasks"></i></span></h3>
    <br>

    <% if notice %>
      <div class="row" style="margin:20px; justify-content:center;">
        <span class="notice"><p><%= notice %></p></span>
      </div>
      <br><br>
    <% end %>

    <span class="count">
      <%= link_to recipe_favorites_toggleFav_path(@recipe), id: 'favorite-link', remote: true do %>
        <%= raw favorite_icon(@recipe, current_user) %>
      <% end %>
      <%= @recipe.favorites.count %>
    </span>

    <br>

    <div class="day">

      <% if user_signed_in? && current_user.id == @recipe.user_id %>
        <%= link_to edit_recipe_path(@recipe) do %>
          <span class="button_tooltip" data-toggle="tooltip" title="編集する" style="float:right;">
            <i class="fas fa-pencil-alt"></i>
          </span>
        <% end %>
      <% end %>
      <h3><b><%= @recipe.title %></b></h3>
    </div>

    <div class="col">
      <br><br>
      <div id="ctg" style="float:right;">
        <% @recipe.recipekinds.each do |rk| %>
          <% if rk.kind == "ご飯" %>
            <%= image_tag("rice.png", :size =>'20x20') %>&ensp;<%= rk.kind %>
          <% elsif rk.kind == "おかず" %>
            <%= image_tag("okazu.png", :size =>'20x20') %>&ensp;<%= rk.kind %>
          <% else %>
            <%= image_tag("soup.png", :size =>'20x20') %>&ensp;<%= rk.kind %>
          <% end %>
        <% end %>
      </div>
      <br><br>
      <i class="fas fa-stopwatch">&ensp;<%= @recipe.cook_min %>min</i>
    </div>

    <br><br>

    <div class="row">

      <div class="col">
        <% if @recipe.img? %>
          <%= image_tag(@recipe.img.url, :size =>'380x280') %>
        <% else %>
          <%=image_tag("no-image1.png", :size =>'380x280') %>
        <% end %>
      </div>

      <div class="col">
        <div class="box1">
          <h5>材料</h5>
          <% @recipe.zairyos.each do |zairyo| %>
          <ul>
            <li>
              <%= zairyo.name %>
              <span style="float:right;"><%= zairyo.kosu %></span>
            </li>
          </ul>
          <% end %>
        </div>
      </div>

      <br><br>



      <div class="col">
        <br><br><br><br>
        <h5>
          <span>つくり方</span>
        </h5>
        <table class="company" style="font-size:1rem;">
          <tbody>
            <% step = 1%>
            <% @recipe.recipeprocesses.each do |process| %>
              <tr>
                <th class="arrow_box"><%= step %></th>
                <td>
                  <%= process.process_txt %>
                </td>
              </tr>
              <% step += 1 %>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
    <br><br><br>
  </div>
  <div class="col">
  </div>
</div>